config/routes.rb
Rails.application.routes.draw do
  root :to => 'flights#search'

  get '/search' => 'flights#search'
  get '/search_results' => 'flights#search_results'

  resources :reservations
  resources :users
  resources :users
  resources :flights
  resources :airplanes

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/flight.rb
# == Schema Information
#
# Table name: flights
#
#  id            :integer          not null, primary key
#  airplane_id   :integer
#  origin        :string
#  destination   :string
#  date          :date
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  flight_number :integer
#  seats         :integer
#

class Flight < ActiveRecord::Base
  has_many :reservations
  belongs_to :airplane

  def self.search(search_origin, search_destination)
    where("origin ILIKE ? AND destination ILIKE ?", "%#{search_origin}%", "%#{search_destination}%")
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
    @flights = @flights.order('date')
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      @flight.seats = Airplane.seat_count(@flight.airplane)
      if @flight.save
        format.html { redirect_to flights_path, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    @flight.seats = Airplane.seat_count(@flight.airplane)
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
  end

  def search_results
    @flights = Flight.all
    if params[:search_origin] && params[:search_destination]
      @flights = Flight.search(params[:search_origin], params[:search_destination]).order("created_at DESC")
    else
      @flights = Flight.all.order("created_at DESC")
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:airplane_id, :origin, :destination, :date, :flight_number, :seats)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :airplane_id %><br>
    <%= f.select :airplane_id, Airplane.pluck(:name, :id),
    {:prompt => 'Select Airplane'}, :class => 'signUpFormSelect' %>
  </div>
  <div class="field">
    <%= f.label :flight_number %><br>
    <%= f.number_field :flight_number, :class => 'signUpForm' %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin, :class => 'signUpForm' %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination, :class => 'signUpForm' %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date, :class => 'signUpForm' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Flights</h1>

<table>
  <thead>
    <tr>
      <th>Airplane</th>
      <th>Flight Number</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Date</th>
      <th>Seats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.airplane.name %></td>
        <td><%= link_to flight.flight_number, flight %></td>
        <td><%= flight.origin %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.date %></td>
        <td><%= flight.seats %></td>
        <% if @current_user.present? && @current_user.admin? %>
          <td><%= link_to 'Show', flight %></td>
          <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
          <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @current_user.present? && @current_user.admin? %>
<%= link_to 'New Flight', new_flight_path, :class => "scaffButton airflightShowButton" %>
<% end %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/search.html.erb
<div id="main">

</div>

<% if @current_user.present? %>
  <%= javascript_tag do %>
    window.currentUserName = "<%= @current_user.name %>";
    window.currentUserID = <%= @current_user.id %>;
  <% end %>
<% end %>

<script type="text/x-template" id="appView">
  <div class="search">
    <h1>Search</h1>
    <div id="searchInput"></div>
  </div>
  <table id="searchResults">
  </table>
</script>


<script type="text/x-template" id="searchInputView">
  <form>
    <select name="" id="searchOrigin">
      <% Flight.pluck('origin').uniq.each do |flight| %>
      <option value="<%= :search_origin %>"><%= flight %></option>
      <% end %>
    </select>
    <select name="" id="searchDestination">
      <% Flight.pluck('destination').uniq.each do |flight| %>
      <option value="<%= :search_destination %>"><%= flight %></option>
      <% end %>
    </select>
    <button class="search_flight">Search</button>
  </form>
</script>


<script id="flightView" type="text/x-template">
  <div class="selectSeat">
    <p class="reservedSeat"></p>
    <button class="seatButton">Select Seat</button>
  </div>

  <div class="seatingMap"></div>
</script>


<script id="searchResult" type="text/x-template">
  <table>

    <tr class="searchResultTR">
      <td>{{= origin }} > </td>
      <td>{{= destination }}</td>
      <td>{{= date }}</td>
      <td class="flight_number" data-id="{{= id }}">{{= flight_number }}</td>
      <td>{{= airplane_id }}</td>
    </tr>
  </table>
</script>

app/views/flights/search_results.html.erb
<h1>Results coming soon</h1>

<% if @flights.blank? %>
  <h4>There are no flights with origins containing the term <%= params[:search_origin] %> or destinations with the term <%= params[:search_destination] %>.</h4>
<% end %>

<table>
  <thead>
    <tr>
      <th>Airplane</th>
      <th>Flight Number</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Date</th>
      <th>Seats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.airplane.name %></td>
        <td><%= link_to flight.flight_number, flight %></td>
        <td><%= flight.origin %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.date %></td>
        <td><%= Airplane.seat_count(flight.airplane) %></td>
        <% if @current_user.present? && @current_user.admin? %>
          <td><%= link_to 'Show', flight %></td>
          <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
          <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Airplane:</strong>
  <%= @flight.airplane.name %>
</p>

<p>
  <strong>Flight Number:</strong>
  <%= @flight.flight_number %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @flight.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Date:</strong>
  <%= @flight.date %>
</p>
<p>
  <strong>Seats:</strong>
  <%= @flight.seats %>
</p>
<% if @current_user.present? && @current_user.admin? %>
  <%= link_to 'Edit', edit_flight_path(@flight) %> |
<% end %>
<%= link_to 'Back', flights_path %>